### ISSUE TITLE
Installation failure for Rmpi

### ISSUE THREAD

**Issue by nstrayer** [accre/R#2]
When I attempt to install Rmpi by way of the readme I run into a couple issues. One of which I have fixed and one of which I haven't. 

**First:** (After doing all prior steps in the readme) I get a no permissions message for installation into `/gpfs22/usr...`. I fixed this by setting my own path for installing libraries in with `export R_LIBS="/home/strayenj/R_Libraries"`. 

**Second:** When I run `R CMD INSTALL Rmpi_0.6-5.tar.gz  --configure-args=--with-mpi=/usr/local/openmpi/1.8.4/x86_64/gcc46` I get this wonderful set of messages: 

```
...
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (14) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[vmps11:19216] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
ERROR: loading failed
...
```

I have checked the paths for openmpi and everything seems to be there but no luck. I have also tried installing in an R instance with 

``` R
install.packages("Rmpi", configure.args =  \\
c("--with-Rmpi-include=/usr/local/openmpi/1.8.4/x86_64/gcc46/include/", \\
"--with-Rmpi-libpath=/usr/local/openmpi/1.8.4/x86_64/gcc46/lib/",  \\
"--with-Rmpi-type=OPENMPI"))
```

to no avail. 

Has anyone else run into this issue and have any idea of how to fix it?

-Nick

**Comment by frenchwr** [comment]
Hey Nick, do you have `setpkgs -a intel_cluster_studio_compiler` in your .bashrc? If so, try removing that, logging out, logging back in, and then attempting the build again. While you're at it (editing your .bashrc), stick `setpkgs -a openmpi_1.8.4` into your .bashrc.

**Comment by nstrayer** [comment]
Hmm, tried both and am still getting the same error. I'll try a different MPI.

@brentonk have you run into this error at all?

**Comment by brentonk** [comment]
I haven't run into it, but that's probably just be because I haven't used Rmpi on ACCRE in months. I've largely moved away from Rmpi and toward just using command args + job arrays because of hard-to-debug memory leak issues I was running into with Rmpi. In any case, I'll try and take a look in the next few days and see if I'm having the same issues with it.

**Comment by nstrayer** [comment]
Got it! 
Had to use MPICH `R CMD INSTALL Rmpi_0.6-5.tar.gz --configure-args="--with-mpi=/usr/local/mpich/3.1.4/nehalem/gcc49/ether/ --with-Rmpi-type=MPICH"` 

I will add this to the readme. 

Thanks for the help!

**Comment by frenchwr** [comment]
Woo hoo! Glad you're up and running. However, we should get this working with other flavors of MPI, so I'm going to reopen this just as a reminder to myself to fight with this when I have time. 

MPICH in particular is not well integrated with SLURM, but I believe there are groups on campus that still actively use it, so you may not run into issues.
